path: /Users/hannojacobs/hanno_bee_types.v2i.yolov8/
train:
- train/images
val:
- valid/images
test:
- test/images

nc: 8
names: ['Allodapula', 'Apis-mellifera-scutellata', 'Braunsapis', 'Lasioglossum', 'Meliponula', 'Seladonia', 'Thyreus', 'Xylocopa']
